In [48]:
import numpy as np
a = np.array([[1, 2], [4, -1]]) #Задаємо матрицю 3*3
b = np.array([[2, -3], [-4, 1]])

print(a-b)

[[-1  5]
 [ 8 -2]]


In [49]:
a = np.array([[-1, 2], [0, 1]])
print(pow(a,2))

[[1 4]
 [0 1]]


In [50]:
a = np.array([[3,5], [6, -1]])
b = np.array([[2,1], [-3, 2]])
print(a*b)

[[  6   5]
 [-18  -2]]


In [51]:
a = np.array([[2,3,4], [1,0,6], [7,8,9]])
print(np.linalg.det(a))

35.00000000000001


In [52]:
a = np.array([[1,2,3,4], [-2,1,-4,3], [3,-4,-1,2], [4,3,-2,-1]])
print(np.linalg.det(a))

900.0000000000009


In [53]:
a = np.array([[1,2,-3], [0,1,2], [0,0,1]])
a_inv = np.linalg.inv(a)
print(a_inv)

[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [54]:
a = np.array([[1,2,3,4], [3,-1,2,5], [1,2,3,4], [1,3,4,5]])
print(np.linalg.matrix_rank(a))

2


In [55]:
a = np.matrix('2 -1 1; 3 4 -2; 1 -3 1')
print('A=',a)
b = np.matrix('5; -3; 4')
print('B=',b)

def kramer (a, b):
    a_det = np.linalg.det(a)
    print('Детермінант матриці = ', a_det)
#Зробити реревірку,що детермінант не дорівнює нулю
    if (a_det != 0):
        print ('Розв*язуємо систему')
        
        x_m = np.matrix(a)
        x_m[:, 0] = b # 1 cт. замінюємо на  ст.b
        print('x_m=', x_m)
        y_m = np.matrix(a)
        y_m[:, 1] = b # 2 cт. замінюємо на  ст.b
        print('y_m=',y_m)

        z_m = np.matrix(a)
        z_m[:, 2] = b # 3 cт. замінюємо на  ст.b
        print('z_m=',z_m)

        x = np.linalg.det(x_m) / a_det
        y = np.linalg.det(y_m) / a_det
        z = np.linalg.det(z_m) / a_det
        print('X = ', round(x,5))

        print('Y=', round(y,5))

        print('Z=', round(z,5))
    else:
        print('Розв*язків немає')
        
kramer(a,b)

A= [[ 2 -1  1]
 [ 3  4 -2]
 [ 1 -3  1]]
B= [[ 5]
 [-3]
 [ 4]]
Детермінант матриці =  -11.999999999999995
Розв*язуємо систему
x_m= [[ 5 -1  1]
 [-3  4 -2]
 [ 4 -3  1]]
y_m= [[ 2  5  1]
 [ 3 -3 -2]
 [ 1  4  1]]
z_m= [[ 2 -1  5]
 [ 3  4 -3]
 [ 1 -3  4]]
X =  1.0
Y= 0.0
Z= 3.0
